import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const positions = [
  // Computer Science
  {
    title: "Graduate Research Assistant - Machine Learning",
    university: "Stanford University",
    department: "Computer Science",
    field_of_study: "computer_science",
    position_type: "research_assistant",
    description: "Seeking a motivated graduate student to assist with cutting-edge machine learning research in our AI lab. Work on neural networks, deep learning, and natural language processing projects. Collaborate with faculty and PhD students on publications.",
    requirements: "Bachelor's in CS or related field, GPA 3.5+, Strong programming skills in Python, Experience with TensorFlow or PyTorch preferred",
    stipend_amount: 40000,
    benefits: "Full tuition waiver, health insurance, conference travel funding",
    hours_per_week: 20,
    location_city: "Stanford",
    location_state: "CA",
    deadline: "2026-02-15",
    start_date: "2026-08-20",
    application_url: "https://stanford.edu/apply",
    contact_email: "mllab@stanford.edu",
  },
  {
    title: "Teaching Assistant - Data Structures",
    university: "MIT",
    department: "Electrical Engineering and Computer Science",
    field_of_study: "computer_science",
    position_type: "teaching_assistant",
    description: "TA position for undergraduate data structures course. Lead recitation sections, hold office hours, grade assignments and exams. Opportunity to develop teaching skills and mentor undergraduates.",
    requirements: "Graduate student in CS/EECS, Strong understanding of algorithms and data structures, Previous TA experience preferred",
    stipend_amount: 38000,
    benefits: "Tuition waiver, health insurance",
    hours_per_week: 20,
    location_city: "Cambridge",
    location_state: "MA",
    deadline: "2026-01-31",
    start_date: "2026-08-25",
    application_url: "https://mit.edu/apply-ta",
    contact_email: "eecs-ta@mit.edu",
  },
  {
    title: "Research Assistant - Cybersecurity Lab",
    university: "Carnegie Mellon University",
    department: "Computer Science",
    field_of_study: "computer_science",
    position_type: "research_assistant",
    description: "Join our cybersecurity research group working on network security, cryptography, and privacy-preserving systems. Contribute to funded NSF projects and publish in top-tier conferences.",
    requirements: "Strong background in systems and security, Programming experience in C/C++ and Python, Interest in research",
    stipend_amount: 42000,
    benefits: "Full tuition, health insurance, research travel",
    hours_per_week: 20,
    location_city: "Pittsburgh",
    location_state: "PA",
    deadline: "2026-03-01",
    start_date: "2026-08-20",
    application_url: "https://cmu.edu/cs/apply",
    contact_email: "cylab-recruit@cs.cmu.edu",
  },

  // Biology
  {
    title: "Graduate Teaching Assistant - Introductory Biology",
    university: "University of California, Berkeley",
    department: "Molecular and Cell Biology",
    field_of_study: "biology",
    position_type: "teaching_assistant",
    description: "Support large introductory biology course. Lead lab sections, assist with lectures, grade assignments, hold office hours. Great opportunity to develop teaching skills.",
    requirements: "Graduate student in Biology or related field, Strong communication skills",
    stipend_amount: 35000,
    benefits: "Tuition remission, health insurance",
    hours_per_week: 20,
    location_city: "Berkeley",
    location_state: "CA",
    deadline: "2026-02-28",
    start_date: "2026-08-15",
    application_url: "https://berkeley.edu/mcb/ta",
    contact_email: "mcb-ta@berkeley.edu",
  },
  {
    title: "Research Assistant - Genetics Lab",
    university: "Harvard University",
    department: "Department of Genetics",
    field_of_study: "biology",
    position_type: "research_assistant",
    description: "Work on CRISPR gene editing projects studying human genetic diseases. Hands-on molecular biology techniques, data analysis, and contribution to publications.",
    requirements: "BS in Biology/Genetics, Molecular biology lab experience, Strong analytical skills",
    stipend_amount: 43000,
    benefits: "Full tuition, health insurance, dental",
    hours_per_week: 20,
    location_city: "Cambridge",
    location_state: "MA",
    deadline: "2026-01-15",
    start_date: "2026-06-01",
    application_url: "https://harvard.edu/genetics/ra",
    contact_email: "genetics-ra@harvard.edu",
  },
  {
    title: "Graduate Research Assistant - Ecology",
    university: "University of Michigan",
    department: "Ecology and Evolutionary Biology",
    field_of_study: "biology",
    position_type: "research_assistant",
    description: "Field-based research on wetland ecosystems and climate change impacts. Collect and analyze ecological data, manage field sites, contribute to NSF-funded project.",
    requirements: "Background in ecology, Field work experience, Valid driver's license, Comfortable working outdoors",
    stipend_amount: 32000,
    benefits: "Tuition waiver, health insurance, field equipment",
    hours_per_week: 20,
    location_city: "Ann Arbor",
    location_state: "MI",
    deadline: "2026-03-15",
    start_date: "2026-05-15",
    application_url: "https://umich.edu/eeb/apply",
    contact_email: "eeb-jobs@umich.edu",
  },

  // Psychology
  {
    title: "Teaching Assistant - Cognitive Psychology",
    university: "Yale University",
    department: "Psychology",
    field_of_study: "psychology",
    position_type: "teaching_assistant",
    description: "Assist with undergraduate cognitive psychology course. Lead discussion sections, grade assignments, help students with research projects.",
    requirements: "Graduate student in Psychology, Background in cognitive psych, Good communication skills",
    stipend_amount: 36000,
    benefits: "Tuition coverage, health insurance",
    hours_per_week: 15,
    location_city: "New Haven",
    location_state: "CT",
    deadline: "2026-02-01",
    start_date: "2026-08-20",
    application_url: "https://yale.edu/psych/ta",
    contact_email: "psych-ta@yale.edu",
  },
  {
    title: "Research Assistant - Clinical Psychology Lab",
    university: "University of Pennsylvania",
    department: "Psychology",
    field_of_study: "psychology",
    position_type: "research_assistant",
    description: "Work on anxiety and depression treatment research. Conduct clinical assessments, manage participant data, assist with study coordination, co-author publications.",
    requirements: "BA/BS in Psychology, Clinical research interest, Experience with SPSS/R preferred, IRB training",
    stipend_amount: 34000,
    benefits: "Tuition remission, health insurance, clinical training",
    hours_per_week: 20,
    location_city: "Philadelphia",
    location_state: "PA",
    deadline: "2026-01-20",
    start_date: "2026-06-01",
    application_url: "https://upenn.edu/psychology/ra",
    contact_email: "psych-lab@upenn.edu",
  },
  {
    title: "Graduate Research Assistant - Developmental Psychology",
    university: "University of Minnesota",
    department: "Institute of Child Development",
    field_of_study: "psychology",
    position_type: "research_assistant",
    description: "Study cognitive and social development in children ages 3-7. Run studies in lab and preschools, code behavioral data, analyze results using statistical software.",
    requirements: "Interest in child development, Experience with children, Programming or stats background helpful",
    stipend_amount: 30000,
    benefits: "Tuition waiver, health insurance",
    hours_per_week: 20,
    location_city: "Minneapolis",
    location_state: "MN",
    deadline: "2026-02-28",
    start_date: "2026-08-25",
    application_url: "https://umn.edu/icd/apply",
    contact_email: "icd@umn.edu",
  },

  // Engineering
  {
    title: "Research Assistant - Robotics Lab",
    university: "Georgia Institute of Technology",
    department: "Mechanical Engineering",
    field_of_study: "engineering",
    position_type: "research_assistant",
    description: "Work on autonomous robotics and computer vision projects. Design, build, and test robotic systems. Collaborate on DARPA-funded research.",
    requirements: "BS in ME/EE/CS, Programming skills (C++, Python), CAD experience, Strong problem-solving abilities",
    stipend_amount: 39000,
    benefits: "Full tuition, health insurance, lab access 24/7",
    hours_per_week: 20,
    location_city: "Atlanta",
    location_state: "GA",
    deadline: "2026-02-15",
    start_date: "2026-08-15",
    application_url: "https://gatech.edu/me/ra",
    contact_email: "robotics@gatech.edu",
  },
  {
    title: "Teaching Assistant - Thermodynamics",
    university: "Purdue University",
    department: "Mechanical Engineering",
    field_of_study: "engineering",
    position_type: "teaching_assistant",
    description: "TA for undergraduate thermodynamics. Conduct lab sessions, grade homework and exams, hold office hours, help students understand complex concepts.",
    requirements: "Graduate student in ME, Solid understanding of thermodynamics, Teaching interest",
    stipend_amount: 28000,
    benefits: "Tuition waiver, health insurance",
    hours_per_week: 20,
    location_city: "West Lafayette",
    location_state: "IN",
    deadline: "2026-03-01",
    start_date: "2026-08-20",
    application_url: "https://purdue.edu/me/ta",
    contact_email: "me-ta@purdue.edu",
  },
  {
    title: "Graduate Research Assistant - Sustainable Energy",
    university: "University of Texas at Austin",
    department: "Electrical and Computer Engineering",
    field_of_study: "engineering",
    position_type: "research_assistant",
    description: "Research on solar energy systems and smart grid technology. Experimental work and simulation. Contribute to DOE-funded project on renewable energy integration.",
    requirements: "BS in EE or related, Interest in renewable energy, MATLAB/Simulink skills, Lab experience",
    stipend_amount: 33000,
    benefits: "Tuition coverage, health insurance, conference travel",
    hours_per_week: 20,
    location_city: "Austin",
    location_state: "TX",
    deadline: "2026-02-01",
    start_date: "2026-08-25",
    application_url: "https://utexas.edu/ece/apply",
    contact_email: "ece-ra@utexas.edu",
  },

  // Education
  {
    title: "Teaching Assistant - Educational Psychology",
    university: "University of Wisconsin-Madison",
    department: "Educational Psychology",
    field_of_study: "education",
    position_type: "teaching_assistant",
    description: "Support graduate-level educational psychology course. Facilitate discussions, grade assignments, meet with students, assist with curriculum development.",
    requirements: "Graduate student in Education or Psychology, Interest in learning theory, Good writing skills",
    stipend_amount: 27000,
    benefits: "Tuition remission, health insurance",
    hours_per_week: 15,
    location_city: "Madison",
    location_state: "WI",
    deadline: "2026-03-15",
    start_date: "2026-08-22",
    application_url: "https://wisc.edu/edpsych/ta",
    contact_email: "edpsych@wisc.edu",
  },
  {
    title: "Research Assistant - STEM Education",
    university: "Northwestern University",
    department: "School of Education and Social Policy",
    field_of_study: "education",
    position_type: "research_assistant",
    description: "Study effectiveness of STEM teaching methods in K-12 schools. Conduct classroom observations, analyze educational data, contribute to research publications.",
    requirements: "Background in education or STEM field, Qualitative research experience, Interest in educational equity",
    stipend_amount: 31000,
    benefits: "Tuition waiver, health insurance, professional development funds",
    hours_per_week: 20,
    location_city: "Evanston",
    location_state: "IL",
    deadline: "2026-01-30",
    start_date: "2026-06-15",
    application_url: "https://northwestern.edu/sesp/ra",
    contact_email: "sesp-jobs@northwestern.edu",
  },

  // Business
  {
    title: "Graduate Research Assistant - Marketing Analytics",
    university: "University of Pennsylvania",
    department: "Wharton School",
    field_of_study: "business",
    position_type: "research_assistant",
    description: "Work with faculty on consumer behavior and marketing analytics research. Analyze large datasets, run experiments, co-author academic papers.",
    requirements: "Strong quantitative skills, Experience with R or Python, Statistics background, Interest in marketing research",
    stipend_amount: 45000,
    benefits: "Full tuition, health insurance, conference funding",
    hours_per_week: 20,
    location_city: "Philadelphia",
    location_state: "PA",
    deadline: "2026-01-15",
    start_date: "2026-08-20",
    application_url: "https://wharton.upenn.edu/ra",
    contact_email: "wharton-ra@wharton.upenn.edu",
  },
  {
    title: "Teaching Assistant - Financial Accounting",
    university: "University of Chicago",
    department: "Booth School of Business",
    field_of_study: "business",
    position_type: "teaching_assistant",
    description: "Support MBA accounting course. Grade case analyses, hold review sessions, assist students with problem sets, provide feedback on presentations.",
    requirements: "Graduate student in Accounting/Finance, CPA track preferred, Strong Excel skills",
    stipend_amount: 40000,
    benefits: "Tuition coverage, health insurance",
    hours_per_week: 15,
    location_city: "Chicago",
    location_state: "IL",
    deadline: "2026-02-28",
    start_date: "2026-09-01",
    application_url: "https://chicagobooth.edu/ta",
    contact_email: "booth-ta@chicagobooth.edu",
  },
]

async function seedPositions() {
  console.log('🌱 Starting to seed positions...')
  console.log(`📊 Inserting ${positions.length} positions...`)
  
  const { data, error } = await supabase
    .from('positions')
    .insert(positions)
    .select()

  if (error) {
    console.error('❌ Error seeding:', error)
    process.exit(1)
  } else {
    console.log(`✅ Successfully seeded ${data.length} positions!`)
    console.log('🎉 Database is ready!')
    process.exit(0)
  }
}

seedPositions()